module.exports={
    devServer:{
        before(app){
            app.get('/api/list',(req,res)=>{
                res.json({
                    code:1
                })
            })
        }
    }
}